title: PCS
description: Control Spotify using your keyboard!
show_downloads: true
github:
  zip_url: https://github.com/UranusDarkness/PCS/releases/latest/download/PCSInstaller.msi
layout: default
theme: jekyll-theme-cayman
