title: HKS
description: Control Spotify with your keyboard!
show_downloads: true
github:
  zip_url: https://github.com/UranusDarkness/HKS/releases/latest/download/HKSInstaller.msi
layout: default
theme: jekyll-theme-cayman
